# Generated by Django 5.2.6 on 2025-09-13 10:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ElectricTwoWheeler",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100)),
                ("company", models.CharField(max_length=100)),
                (
                    "battery_capacity",
                    models.DecimalField(
                        decimal_places=2, help_text="kWh", max_digits=5
                    ),
                ),
                (
                    "range_per_charge",
                    models.PositiveIntegerField(help_text="Range in km"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=6)),
                ("color", models.CharField(max_length=30)),
                (
                    "image1",
                    models.ImageField(blank=True, null=True, upload_to="two_wheelers/"),
                ),
                (
                    "image2",
                    models.ImageField(blank=True, null=True, upload_to="two_wheelers/"),
                ),
                (
                    "image3",
                    models.ImageField(blank=True, null=True, upload_to="two_wheelers/"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
