# Generated by Django 5.2.6 on 2025-09-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ev_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="electrictwowheeler",
            name="price",
            field=models.IntegerField(),
        ),
    ]
