# Generated by Django 5.2.6 on 2025-09-17 07:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ev_app", "0003_review_reviewimage"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviewimage",
            name="review",
        ),
        migrations.DeleteModel(
            name="Review",
        ),
        migrations.DeleteModel(
            name="ReviewImage",
        ),
    ]
